---
output: 
  md_document:
    variant: markdown_phpextra
---

## 14 Sums and Asymptotics

和乘积在算法分析、金融应用、物理问题和概率系统中定期出现。例如，根据定理2.2.1,

$$
1 + 2 + 3 + \cdots + n = \frac{n(n + 1)}{2}
$$

当然，左边的和可以用带下标的求和符号简洁地表示

$$
\sum_{i=1}^n i
$$

但右边的表达式 $\frac{n(n + 1)}{2}$ 不仅简洁，而且更容易计算。此外，它更清楚地揭示了和的增长率等属性。像 $\frac{n(n + 1)}{2}$ 这样的表达式不使用带下标的求和或乘积符号——或者那些方便但有时麻烦的三点序列——被称为**闭式表达式**。

另一个例子是几何和的闭式表达式

$$
1 + x + x^2 + x^3 + \cdots + x^n = \frac{1 - x^{n+1}}{1 - x}
$$

在问题5.4中给出。像(14.2)左边描述的和涉及 $n$ 次加法，而 $1 + 2 + \cdots + (n - 1) = (n - 1)n/2$ 次乘法，但它的闭式右边可以用快速指数计算，最多只需$2 \log n$ 次乘法、一次除法和几次减法。此外，闭式表达使和的增长和限制行为更明显。

方程(14.1)和(14.2)容易通过归纳法验证，但正如通常情况，归纳法的证明没有提示这些公式是如何找到的。找到它们部分是数学，部分是艺术，我们将在本章开始研究。

我们第一个激励的例子是称为年金的金融工具的价值。这个值将是一个庞大而讨厌的值。然后我们将描述几种方法来找到年金等几种类型和的闭式。在某些情况下，和的闭式可能不存在，因此我们将提供一种通用方法来找到和的良好上限和下限。

本章将使用这种方法找到阶乘函数的良好闭式近似

$$
n! ::= 1 \cdot 2 \cdot 3 \cdots n
$$

我们以讨论渐近符号结束本章，特别是“大O”符号。渐近符号常用于在没有确切闭式表达式时界定和或积的误差项。它还提供了一种方便的方法来表示和或积的增长率或数量级。

### 14.1 年金的价值

你会选择今天拿到一百万美元，还是在余生中每年拿到五万美元？一方面，立即满足感很好。另一方面，如果你活得足够久，每年拿到五万美元的总金额会大得多。

正式地说，这是一个关于年金价值的问题。年金（annuity）是一种金融工具，每年初支付固定金额的钱，持续若干年。特别地，一个n年期、每年支付m美元的年金在每年的开始支付m美元，共持续n年。在某些情况下，n是有限的，但并不总是如此。例子包括彩票支付、学生贷款和房屋抵押贷款。甚至有华尔街的公司专门从事年金交易。

一个关键问题是，“年金值多少钱？”例如，彩票经常在许多年里支付大奖。直观地说，20年内每年支付五万美元应该不如现在拿到一百万美元值钱。如果你现在就拿到所有现金，你可以投资它并开始赚取利息。但如果选择在未来20年内每年支付五万美元和现在拿到五十万美元之间，该如何决定呢？突然之间，哪个选择更好并不那么清楚了。

#### 14.1.1 货币的未来价值

为了回答这样的问题，我们需要知道未来支付的一美元在今天值多少钱。为了模拟这一点，假设钱可以以年利率p进行固定投资。为了便于讨论，我们假设利率为8%，因此$p = 0.08$。

这是利率p很重要的原因。今天投资十美元，以利率p一年后将变成$10 \cdot (1 + p) = 10.80$美元，两年后变成$10 \cdot (1 + p)^2 = 11.66$美元，依此类推。换句话说，现在支付的十美元实际上只值$10 / (1 + p) \approx 9.26$美元，因为如果我们今天有这笔钱，我们可以投资它并在一年后拥有10美元。因此，p决定了未来支付的钱的价值。

对于一个n年期、每年支付m美元的年金，第一年的支付m美元实际上值m美元。但第二年的支付只值$m / (1 + p)^1$美元，同样，第三年的支付值$m / (1 + p)^2$美元，依此类推。总的年金价值V等于支付值的总和。如下所示：

$$
V = \sum_{i=1}^n \frac{m}{(1+p)^{i-1}} = m \cdot \sum_{j=0}^{n-1} \left(\frac{1}{1+p}\right)^j
$$

目标是将求和转换为简单的几何和的形式。这引出了我们可以使用摄动法来发现闭式形式的解释。

#### 14.1.2 摄动法

给定一个具有良好结构的和，通常使用“摄动”这个和，以便将和与摄动结合起来，得到一个更简单的形式。例如，假设

$$
S = 1 + x + x^2 + \cdots + x^n
$$

一个摄动例子是

$$
xS = x + x^2 + \cdots + x^{n+1}
$$

减去xS和S：

$$
S - xS = 1 - x^{n+1}
$$

求解S得到所需的闭式形式：

$$
S = \frac{1 - x^{n+1}}{1 - x}
$$

我们将在第16章介绍生成函数时看到更多这种方法的例子。

#### 14.1.3 年金价值的闭式形式

使用方程14.2，我们可以导出一个简单的公式来计算年金的价值V，该年金在每年初支付m美元，共持续n年。

$$
V = m \left(\frac{1 - x^n}{1 - x}\right) = m \left(\frac{1 + p - (1 / (1 + p))^n}{p}\right)
$$

方程14.5比具有数十项的求和式更容易使用。例如，一个每年支付五万美元，持续20年的彩票中奖的真实价值是多少？代入$m = \$50,000$，$n = 20$，$p = 0.08$得出$V \approx \$530,180$。由于付款是延迟的，因此一百万美元的彩票实际上只值大约五十万美元！这对广告商来说是一个好把戏。

#### 14.1.4 无限几何级数

我们开始本章时提出的问题是你是否会选择今天的一百万美元，还是余生中每年五万美元。当然，这取决于你能活多久，所以乐观地假设第二种选择是每年永远收到五万美元。这听起来像是无限的钱！但是我们可以通过将几何和取极限来计算带有无限支付的年金的价值。

**定理 14.1.1**

如果$|x| < 1$，则

$$
\sum_{i=0}^{\infty} x^i = \frac{1}{1 - x}
$$

**证明：**

$$
\sum_{i=0}^{\infty} x^i ::= \lim_{n \to \infty} \sum_{i=0}^n x^i = \lim_{n \to \infty} \frac{1 - x^{n+1}}{1 - x} = \frac{1}{1 - x}
$$

在我们的年金问题中，$x = \frac{1}{1 + p} < 1$，因此定理14.1.1适用，我们得到

$$
V = m \cdot \sum_{j=0}^{\infty} x^j = m \cdot \frac{1}{1 - x} = m \cdot \frac{1 + p}{p}
$$

代入$m = \$50,000$和$p = 0.08$，我们看到年金的价值仅为$V = \$675,000$。看起来今天的一百万美元要比永远每年支付五万美元值钱得多！但仔细检查，如果我们今天在银行有一百万美元，年利率8%，我们可以每年取出并花费八万美元，**永远**。所以事实证明，这个答案并不像看起来那么神奇。

#### 14.1.5 例子

方程14.2和定理14.1.1在计算机科学中非常有用。以下是一些可以使用方程14.2和定理14.1.1放入闭式形式的常见和：

$$
1 + \frac{1}{2} + \frac{1}{4} + \cdots = \sum_{i=0}^{\infty} \left(\frac{1}{2}\right)^i = \frac{1}{1 - (1/2)} = 2
$$

$$
0.99999\cdots = 0.9 \sum_{i=0}^{\infty} \left(\frac{1}{10}\right)^i = 0.9 \left(\frac{1}{1 - 1/10}\right) = 0.9 \left(\frac{10}{9}\right) = 1
$$

$$
1 - \frac{1}{2} + \frac{1}{4} - \cdots = \sum_{i=0}^{\infty} \left(-\frac{1}{2}\right)^i = \frac{1}{1 - (-1/2)} = \frac{2}{3}
$$

$$
1 + 2 + 4 + \cdots + 2^{n-1} = \sum_{i=0}^{n-1} 2^i = \frac{1 - 2^n}{1 - 2} = 2^n - 1
$$

$$
1 + 3 + 9 + \cdots + 3^{n-1} = \sum_{i=0}^{n-1} 3^i = \frac{1 - 3^n}{1 - 3} = \frac{3^n - 1}{2}
$$

如果几何和的项逐渐变小，如方程14.6中所示，那么该和被称为**几何递减和**。如果几何和的项逐渐变大，如方程14.9和14.10中所示，那么该和被称为**几何递增和**。在任何一种情况下，该和通常大致等于具有最大绝对值的项。例如，在方程14.6和14.8中，最大项等于1，和分别为2和2/3，都相对接近1。在方程14.9中，和大约是最大项的两倍。在方程14.10中，最大项是$3^{n-1}$，和是$(3^n - 1)/2$，仅大约大1.5倍。通过仔细观察

方程14.2和定理14.1.1，你可以理解这个经验法则为什么有效。

#### 14.1.6 几何和的变体

我们现在了解了几何和——如果有一个，生活就简单了。但是在实践中，人们经常遇到不能通过简单的变量替换转换为$\sum x^i$形式的和。获得新求和公式的一种不显而易见但有用的方法是对x求导或积分。作为一个例子，考虑以下和：

$$
\sum_{i=1}^{n-1} ix^i = x + 2x^2 + 3x^3 + \cdots + (n-1)x^{n-1}
$$

这不是几何和。连续项之间的比率不是固定的，因此我们不能直接应用几何和的公式。但对方程14.2求导得到：

$$
\frac{d}{dx} \left(\sum_{i=0}^{n-1} x^i\right) = \frac{d}{dx} \left(\frac{1 - x^n}{1 - x}\right)
$$

方程14.11的左侧是简单的

$$
\sum_{i=0}^{n-1} \frac{d}{dx} \left(x^i\right) = \sum_{i=0}^{n-1} ix^{i-1}
$$

方程14.11的右侧是

$$
\frac{-nx^{n-1}(1-x) - (1)(1-x^n)}{(1-x)^2} = \frac{1 - nx^{n-1} + (n-1)x^n}{(1-x)^2}
$$

因此，方程14.11意味着

$$
\sum_{i=0}^{n-1} ix^{i-1} = \frac{1 - nx^{n-1} + (n-1)x^n}{(1-x)^2}
$$

问题14.2显示了如何将摄动法应用于推导此公式。通常，求导或积分会弄乱每一项中的x指数。在这种情况下，我们现在有了$\sum_{i=0}^{n-1} ix^{i-1}$形式的公式，但我们想要$\sum ix^i$的公式。解决方法很简单：乘以x。这样得到：

$$
\sum_{i=1}^{n-1} ix^i = \frac{x - nx^n + (n-1)x^{n+1}}{(1-x)^2}
$$

我们得到了所需的闭式和公式。虽然看起来有些复杂，但比直接处理和更容易。

注意如果$|x| < 1$，则该级数收敛到有限值，即使有无限多项。取方程14.12的极限得到以下定理：

**定理 14.1.2**

如果$|x| < 1$，则

$$
\sum_{i=1}^{\infty} ix^i = \frac{x}{(1-x)^2}
$$

因此，假设有一个年金，每年i的年末支付$im$美元，持续永远。例如，如果$m = \$50,000$，那么支付依次为$\$50,000$，然后$\$100,000$，然后$\$150,000$等等。很难相信这个年金的价值是有限的！但我们可以使用定理14.1.2计算其价值：

$$
V = \sum_{i=1}^{\infty} \frac{im}{(1+p)^i} = m \cdot \frac{\frac{1}{(1+p)}}{(1 - \frac{1}{1+p})^2} = m \cdot \frac{1 + p}{p^2}
$$

第二行通过应用定理14.1.2来计算这个值

$$
\begin{aligned}
V & =\sum_{i=1}^{\infty} \frac{i m}{(1+p)^i} \\
& =m \cdot \frac{1 /(1+p)}{\left(1-\frac{1}{1+p}\right)^2} \\
& =m \cdot \frac{1+p}{p^2}
\end{aligned}
$$

第二行通过应用定理 14.1.2 得到。第三行是通过将分子和分母同时乘以 $(1 + p)^2$ 得到的。 例如，如果 $m = \$50,000$，并且 $p = 0.08$ 如常，那么年金的价值 $V = \$8,437,500$。尽管支付每年增加，但增加只是随时间线性增加；相比之下，未来支付的美元价值则以指数方式递减。几何递减淹没了线性增加。遥远未来的支付几乎一文不值，因此年金的价值是有限的。 需要记住的重要一点是对求和公式进行导数（或积分）的技巧。当然，这种方法要求正确地计算复杂的导数，但这至少在理论上是可行的！
