---
output: 
  md_document:
    variant: markdown_phpextra
---

# 教科书和参考资料

这个书单可能已经比较老旧了. (由于现在没有时间打比赛, 这方面的书本也读得少了)此大家有推荐的教科书, 欢迎告诉我！同时, 大语言模型也冲击传统的学习方式：正确地提问将是未来学习中最重要的技能. 当然无论如何, 我们都建议大家多读书：

-   算法中的很多知识是关联的, 因此你对某一部分的理解都会加深对这方面的理解；反之也一样. 认识通常是 “螺旋式上升” 的；

-   竞赛的算法的内容不是纸上谈兵, 因此学习很多技术是非常重要的, 例如如何使用调试器, 如何debug. 通常网页的参考手册可以帮助你理解一些实用技巧.

-   每一本书的作者都有他们独到的视角 (某些为了凑数编教材而编教材的除外). 因此也许某个作者的思维方式就特别适合你, 读起来就会很轻松.

## 教科书

-   算法竞赛入门经典 刘汝佳等 (紫书)

这系列教科书可以当做指引. 如果大家自学的话, 可能有一些画外音会漏掉. 当然, 这对于受过\~2年正规的高等教育的同学来讲, 画外音会更多地被捕捉.

我们会拿它当做大部分例题的来源. 希望大家好好体会. 同时书中很多代码的书写很规范, 赏心悦目.

## 参考资料

### 1. 大语言模型

吸收了天地精华的大语言模型, 平时请你向他们提问. 对他们的回答请谨慎求证.

例如Deepseek是一个水平尚可的大语言模型. 但是有时候还是会犯错误.

### 2. 竞赛技巧

这些内容可能不是非常适合初学者, 文本的质量和水平都有所下降. 不过, 还是推荐大家多加阅读. 如果能够识别出来哪里不足就更好了.

### 3. 最后, the friendly manual

-   [**Bourne-Again Shell (bash)**](https://www.gnu.org/software/bash/manual/html_node/index.html)

-   [**GNU Compiler Collection (GCC)**](https://gcc.gnu.org/onlinedocs/)

-   [**GNU Debugger (gdb)**](https://sourceware.org/gdb/documentation/)
